# Generated by Django 5.1.4 on 2025-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
